apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/add-base-url: "true"
#    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:4200"
spec:
  rules:
     - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: fe
              servicePort: 80
          - path: /first/(.*)
            backend:
              serviceName: web
              servicePort: 3000
          - path: /second/(.*)
            backend:
              serviceName: web2
              servicePort: 3003
