apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
     - http:
        paths:
          - path: /first/(.*)
            backend:
              serviceName: web
              servicePort: 3000
          - path: /second/(.*)
            backend:
              serviceName: web2
              servicePort: 3003
