name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        secreto: ${{  secrets.first_secret }}
      run: |
        cd first
        echo secreto
        ./testScript.sh
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
